# Retail Properties: Data Cleaning + EDA

In this notebook, we will be examining the raw dataset (pca_retail_building_section_1&4&5.csv), cleaning the data, and performing exploratory data analysis.

<hr>

## Examining the Raw Dataset

Importing the raw dataset and identifying NA values and inconsistencies.

In [ ]:
# Importing libraries for EDA
import pandas as pd

# Read in raw dataset
retail = pd.read_csv('pca_retail_building_section_1&4&5_data_items.csv')

### Displaying RETAIL Data Overview

In [ ]:
# Display RETAIL Data Overview
retail.head(50)

id  project_id                                   document_spot  \
0   64098211      621709                                      541b_wall1   
1   64099519      621709                                        542a_esc   
2   64099836      621709                               551_fire_hydrants   
3   64102647      621709                               pca_reserve_yn_8a   
4   64070020      623951                                553b_othrsysdesc   
5   64099948      621709                               552_smoke_det_loc   
6   64099832      621709                               551p_fire_ex_cond   
7   64098144      621709                                     53m_stablok   
8   64095621      621709                              pca_reserve_yn_36a   
9   64098089      621709                                      53a_transf   
10  64103592      621709                               1zp_build_address   
11  64100043      621709                          431dd_facade_ordinance   
12  63983352      621170                                  01q_client_zip   
13  64099874      621709                                     552b_detloc   
14  64099864      621709                                   552aa_fa_comp   
15  64100127      621709                              pca_reserve_yn_65a   
16  64103635      621709                                1i_eul_statement   
17  64100141      621709                                      451_1f_pca   
18  64100049      621709                                       432a_wind   
19  64103574      621709                                  pca_01_eff_age   
20  64103653      621709                                     45h_fbscond   
21  64099534      621709                                      551a_fsupp   
22  64098228      621709                                  541aa_elevcond   
23  64103637      621709                    1m_additional_investigations   
24  64099541      621709                                  551b_fsuppserv   
25  64097384      621709                                      51a_domrep   
26  64097937      621709                              pca_reserve_yn_23a   
27  64097622      621709                                     51ba_whcond   
28  64103651      621709                              pca_reserve_yn_19a   
29  64098133      621709                    53_unit_individually_metered   
30  64098150      621709                                       53_4a_pca   
31  64100134      621709                              pca_reserve_yn_66a   
32  64100071      621709                                433dp_oh_door_op   
33  63983351      621170                                01p_client_state   
34  64103647      621709                                      442a_drain   
35  64100169      621709                                    45g_balcrail   
36  64099857      621709                                      552_1a_pca   
37  64099809      621709                                      551_1b_pca   
38  64097383      621709                                   51b_dompipobs   
39  64100162      621709                                     45f_balctyp   
40  64098206      621709                        elevator_manufacture_541   
41  64097880      621709                                      52a_1b_pca   
42  64099522      621709                                        542b_esc   
43  64099804      621709                                   551h_suppinsp   
44  64102615      621709                              pca_reserve_yn_50a   
45  63983341      621170                                01c_project_city   
46  64098111      621709  amperage_supplied_to_main_switchgearpanel_53sb   
47  64100051      621709                                   432c_windcond   
48  64100076      621709                              pca_reserve_yn_17a   
49  64099986      621709                                   42b_horzconst   

                                         outside_name  \
0                                          541b_wall1   
1                  

### Initial Observations

- ~2% of the values are missing in the outside_name column. outside_name represents the variable name that is shown to users on the property assessment report. This may vary in the full dataset as this is only in the first 50 rows we see.

- We may choose to drop outside_name, but may also not since document_spot may be able to provide the same information.

- 40% of the values are missing in the column. This is not a worry, as document_text is an optional field for users to input additional information about their property in the reporting process, so we can just ignore these.

### Looking at full RETAIL Data

In [ ]:
retail

id  project_id        document_spot  \
0       64098211      621709           541b_wall1   
1       64099519      621709             542a_esc   
2       64099836      621709    551_fire_hydrants   
3       64102647      621709    pca_reserve_yn_8a   
4       64070020      623951     553b_othrsysdesc   
...          ...         ...                  ...   
558412  59679704      609229          53m_stablok   
558413  59604146      609647      441ap_flash_mat   
558414  59679944      609229   pca_reserve_yn_13a   
558415  59679351      609229  01zp_project_county   
558416  59601970      609647        433ap_oh_door   

                               outside_name  \
0                                541b_wall1   
1                are_escalators_present_542   
2                         551_fire_hydrants   
3                         pca_reserve_yn_8a   
4             other_systems_description_553   
...                                     ...   
558412  federal_pacific_stab_lok_present_53   
558413                      441ap_flash_mat   
558414                   pca_reserve_yn_13a   
558415                  01zp_project_county   
558416                        433ap_oh_door   

                                                 the_data  \
0                                               ["Metal"]   
1                                                     yes   
2                                                     yes   
3                                                      no   
4       Emergency lighting was typically provided by c...   
...                                                   ...   
558412                                               none   
558413                    ["Similar to roofing membrane"]   
558414                                                 no   
558415                                             Sussex   
558416                            ["Steel panel roll-up"]   

                                            document_text section_reference  \
0                                     metal wall finishes             5.4.1   
1                                                     NaN             5.4.2   
2                                                     NaN             5.5.1   
3                                                     NaN               1.0   
4       Emergency lighting was typically provided by c...             5.5.3   
...                                                   ...               ...   
558412                                                NaN               5.3   
558413  Flashing materials appeared to be similar to t...             4.4.1   
558414                                                NaN               1.0   
558415                                             Sussex                 1   
558416  The overhead doors consisted of steel panel ro...             4.3.3   

                     type  
0       PcaReportDataItem  
1       PcaReportDataItem  
2       PcaReportDataItem  
3       PcaReportDataItem  
4       PcaReportDataItem  
...                   ...  
558412  PcaReportDataItem  
558413  PcaReportDataItem  
558414  PcaReportDataItem  
558415  PcaReportDataItem  
558416  PcaReportDataItem  

[558417 rows x 8 columns]

<hr>

## Examining NA Values

In [ ]:
# Counting NA values for all columns
na_count = retail.isna().sum()
print(na_count)

id                        0
project_id                0
document_spot             0
outside_name           3958
the_data                  0
document_text        148653
section_reference         0
type                      0
dtype: int64


There are 3958 rows of missing outside_name data. This is ~0.007% of the full retail data. Because we are going to use document_spot for attributing a row to a specific value for a structural attribute, we can ignore the NA's in outside_name.

<hr>

## Examining Unique Values

### Looking at the unique values of document_spot, section_reference

document_spot is the attribute field as shown in the PCA report

section_reference is the section that the attribute field is located in the PCA report

In [ ]:
# All of the unique property attributes in our data
retail['document_spot'].unique()

array(['541b_wall1', '542a_esc', '551_fire_hydrants', 'pca_reserve_yn_8a',
       '553b_othrsysdesc', '552_smoke_det_loc', '551p_fire_ex_cond',
       '53m_stablok', 'pca_reserve_yn_36a', '53a_transf',
       '1zp_build_address', '431dd_facade_ordinance', '01q_client_zip',
       '552b_detloc', '552aa_fa_comp', 'pca_reserve_yn_65a',
       '1i_eul_statement', '451_1f_pca', '432a_wind', 'pca_01_eff_age',
       '45h_fbscond', '551a_fsupp', '541aa_elevcond',
       '1m_additional_investigations', '551b_fsuppserv', '51a_domrep',
       'pca_reserve_yn_23a', '51ba_whcond', 'pca_reserve_yn_19a',
       '53_unit_individually_metered', '53_4a_pca', 'pca_reserve_yn_66a',
       '433dp_oh_door_op', '01p_client_state', '442a_drain',
       '45g_balcrail', '552_1a_pca', '551_1b_pca', '51b_dompipobs',
       '45f_balctyp', 'elevator_manufacture_541', '52a_1b_pca',
       '542b_esc', '551h_suppinsp', 'pca_reserve_yn_50a',
       '01c_project_city',
       'amperage_supplied_to_main_switchgearpanel_

In [ ]:
# All of the unique sections in our data
retail['section_reference'].unique()

array(['5.4.1', '5.4.2', '5.5.1', '1.0', '5.5.3', '5.5.2', '5.3', '4.3.1',
       '1', '4.4.1', '4.5', '4.3.2', '5.1', '4.3.3', '4.4.2', '5.2',
       '4.2', '4.3', '4.1', '4.4', '4.4.3', '5.4.1.3', '5.4', '5.3.2',
       '5.1.2', '5.0', '5.4.1.2', '5.3.3', '1.6', '5.5.1.2', '5.1.3',
       '4.5.3', '4.5.2', '4.5.1', '5.4.1.4'], dtype=object)

The attributes and sections align with our knowledge that we are working with attributes from sections 1 (exec), 4, and 5 of the Property Condition Assessment reports.

<hr>

### Looking at the unique values of id

We are presuming id is distinct for each row as we believe it represents the id for the specific attribute input for a given property.

In [ ]:
# Count the number of unique values in id
retail['id'].nunique()

558417

There are 558417 unique id's in the data set. This confirms that id is unique to each row. We will drop this column as it will not be useful to our analysis.

<hr>

### Looking at the unique value of project_id

In [ ]:
# Count the number of unique values in project_id (the property)
retail['project_id'].nunique()

2891

In [ ]:
# Count the number of occurrences for each unique value in project_id
retail['project_id'].value_counts()

project_id
564120    475
377788    337
559307    335
571408    315
593867    295
         ... 
356705     22
341562     21
618136     20
621305     20
621170     20
Name: count, Length: 2891, dtype: int64

There is a total of 2891 unique projects. Not every project_id has the same number of attributes associated with it. We don't know if this is due to some PCA reports not being completely filled out, but we can proceed to isolate the attributes we'd like to examine.

<hr>

## Simplifying RETAIL data

We are simplifying RETAIL to just include the project_id, document_spot, and the_data columns.

In [ ]:
# Simplify RETAIL
retail_simplified = retail[['project_id', 'document_spot', 'the_data']]
retail_simplified

project_id        document_spot  \
0           621709           541b_wall1   
1           621709             542a_esc   
2           621709    551_fire_hydrants   
3           621709    pca_reserve_yn_8a   
4           623951     553b_othrsysdesc   
...            ...                  ...   
558412      609229          53m_stablok   
558413      609647      441ap_flash_mat   
558414      609229   pca_reserve_yn_13a   
558415      609229  01zp_project_county   
558416      609647        433ap_oh_door   

                                                 the_data  
0                                               ["Metal"]  
1                                                     yes  
2                                                     yes  
3                                                      no  
4       Emergency lighting was typically provided by c...  
...                                                   ...  
558412                                               none  
558413                    ["Similar to roofing membrane"]  
558414                                                 no  
558415                                             Sussex  
558416                            ["Steel panel roll-up"]  

[558417 rows x 3 columns]

<hr>

## Data Cleaning

LEGEND

document_spot: the variable name according to the PCA report

the_data: the input data

project_id: unique id for the property

## Looking at the number of buildings per PCA report

If the number of buildings (1c_summary_building_number) is greater than 1, we can remove from our analysis.

In [ ]:
# What are the unique value that could be inputted for 1c_summary_building_num
retail_simplified[retail_simplified['document_spot'] == '1c_summary_building_num']['the_data'].unique()

array(['2', '5', '1', '8', 'Five and one under construction', '3', '4',
       '6', '13', '20', '7', 'One (1)',
       '13 (includes five ground lease buildings which were not assessed)',
       '11', 'One (w/ One Storage Garage)', '15', '9',
       'Two (Buildings 1 through 6 are adjoining; Building 7 is stand-along)',
       '10', 'One', '14', '21', '0', '33', 'Four', '25',
       'Seven including three land lease buildings', 'Three',
       'Three + Jungle Plaza', '16'], dtype=object)

We only want the buildings with 'One' and '1' in the input.

In [ ]:
# Looking at the project_id's that have multiple buildings
multiple_buildings = retail_simplified[(retail_simplified['document_spot'] == '1c_summary_building_num') & 
                                        (retail_simplified['the_data'] > '1')]
multiple_buildings

project_id            document_spot                         the_data
745         580845  1c_summary_building_num                                2
934         457720  1c_summary_building_num                                5
1123        398107  1c_summary_building_num                                8
1968        445385  1c_summary_building_num                                2
2560        381397  1c_summary_building_num  Five and one under construction
...            ...                      ...                              ...
552093      480322  1c_summary_building_num                                4
552126      479702  1c_summary_building_num                                5
552719      455381  1c_summary_building_num                               16
555290      488072  1c_summary_building_num                                2
555515      580834  1c_summary_building_num                                4

[693 rows x 3 columns]

In [ ]:
# Checking if we filtered correctly
multiple_buildings['the_data'].unique()

array(['2', '5', '8', 'Five and one under construction', '3', '4', '6',
       '13', '20', '7', 'One (1)',
       '13 (includes five ground lease buildings which were not assessed)',
       '11', 'One (w/ One Storage Garage)', '15', '9',
       'Two (Buildings 1 through 6 are adjoining; Building 7 is stand-along)',
       '10', 'One', '14', '21', '33', 'Four', '25',
       'Seven including three land lease buildings', 'Three',
       'Three + Jungle Plaza', '16'], dtype=object)

There are still properties here with 'One', which means they only have one building. We want to exclude that. 

In [ ]:
# Exclude properties that have 'One' building
multiple_buildings2 = multiple_buildings[~multiple_buildings['the_data'].str.contains('One')]

multiple_buildings2

project_id            document_spot                         the_data
745         580845  1c_summary_building_num                                2
934         457720  1c_summary_building_num                                5
1123        398107  1c_summary_building_num                                8
1968        445385  1c_summary_building_num                                2
2560        381397  1c_summary_building_num  Five and one under construction
...            ...                      ...                              ...
552093      480322  1c_summary_building_num                                4
552126      479702  1c_summary_building_num                                5
552719      455381  1c_summary_building_num                               16
555290      488072  1c_summary_building_num                                2
555515      580834  1c_summary_building_num                                4

[685 rows x 3 columns]

### Dropping properties with multiple buildings

In [ ]:
# The unique properties with multiple buildings
drop_properties = multiple_buildings2['project_id'].unique()
# Number of properties we need to drop
len(drop_properties)

685

Dropping the buildings from retail_simplified with the same project_id in drop_properties.

In [ ]:
# Dropping rows from retail_simiplified that have the same project_id in drop_properties
retail_simplified = retail_simplified[~retail_simplified['project_id'].isin(drop_properties)]
retail_simplified['project_id'].nunique()

2206

retail_simplified is now clean!

### Exporting retail_simplified

In [ ]:
# Export retail_simplified to folder
retail_simplified.to_csv('Clean Retail Data/retail_simple.csv', index=False)

<hr>

### Dropping duplicate rows (project_id, document_spot, the_data)

In [ ]:
retail_simplified = retail_simplified.drop_duplicates(subset=['project_id', 'document_spot', 'the_data'])

<hr>

## Examining Retail analysis attributes

We want to see if there are properties with multiple inputs for the same attribute. We are going to look at the unique number of project_id's for the following attributes

- zipcode (01e_project_zip)

- square footage (1f_summary_gross_building)

- construction (42a_vertconst, 42b_horzconst)

### Zipcodes

In [ ]:
# Looking at the unique number of project_id for zip code attributes in retail_simplified
zipcodes = retail_simplified[retail_simplified['document_spot'] == '01e_project_zip']
num_zip = len(zipcodes)
uniq_zip = zipcodes['project_id'].nunique()
print('Number of zipcode attributes: ', num_zip)
print('Number of properties with zipcodes: ', uniq_zip)

Number of zipcode attributes:  2205
Number of properties with zipcodes:  2205


There is no property with multiple zipcode attributes.

### Looking for odd zipcodes

Zipcodes must satisfy the following

- 5 digits long

- Digits only

In [ ]:
# Finding the rows with non-numeric zipcodes
not_all_digits = zipcodes[zipcodes['the_data'].str.contains('[a-zA-Z]')]
not_all_digits

project_id    document_spot the_data
205929      472606  01e_project_zip  V7J 2C4

In [ ]:
# Finding the rows with zipcodes that is not 5 digits
not_5_digits = zipcodes[zipcodes['the_data'].str.len() != 5]
not_5_digits

project_id    document_spot    the_data
51945       248443  01e_project_zip        6320
205929      472606  01e_project_zip     V7J 2C4
314345      318910  01e_project_zip     85295  
438871      441205  01e_project_zip  48038-3503
462112      258978  01e_project_zip        7960

There are 5 zipcodes that do not have 5 digits. Of them, project_ids 472606, 258978, and 248443 can be removed as it does not meet the zipcode guidelines. As for the rest, it seems to be a clerical issue which we can manually resolve.

In [ ]:
# Just taking out the first 5 digits
drop_properties_full = not_5_digits['project_id']
drop_properties = [472606, 258978, 248443]
not_5_digits = not_5_digits[~not_5_digits['project_id'].isin(drop_properties)]

not_5_digits.loc[:, 'the_data'] = not_5_digits['the_data'].str[:5]
not_5_digits

project_id    document_spot the_data
314345      318910  01e_project_zip    85295
438871      441205  01e_project_zip    48038

In [ ]:
# Removing the faulty properties
zipcodes = zipcodes[~zipcodes['project_id'].isin(drop_properties_full)]

In [ ]:
# Concatenating the fixed zipcodes
zipcodes = pd.concat([zipcodes, not_5_digits], ignore_index=True)

zipcodes

project_id    document_spot the_data
0         621170  01e_project_zip    94114
1         402102  01e_project_zip    06902
2         409030  01e_project_zip    33624
3         376933  01e_project_zip    92672
4         507879  01e_project_zip    78207
...          ...              ...      ...
2197      339630  01e_project_zip    91367
2198      379235  01e_project_zip    27284
2199      332265  01e_project_zip    75062
2200      318910  01e_project_zip    85295
2201      441205  01e_project_zip    48038

[2202 rows x 3 columns]

Double-checking !

In [ ]:
# Looking at the unique number of project_id for zip code attributes in retail_simplified
num_zip = len(zipcodes)
uniq_zip = zipcodes['project_id'].nunique()
print('Number of zipcode attributes: ', num_zip)
print('Number of properties with zipcodes: ', uniq_zip)

Number of zipcode attributes:  2202
Number of properties with zipcodes:  2202


<hr>

### Sqft

In [ ]:
# Looking at the unique number of project_id for square foot attributes in retail_simplified
sq_foots = retail_simplified[retail_simplified['document_spot'] == '1f_summary_gross_building']
num_sf = len(sq_foots)
uniq_sf = sq_foots['project_id'].nunique()
print('Number of square foot attributes: ', num_sf)
print('Number of properties with square footage: ', uniq_sf)

Number of square foot attributes:  2186
Number of properties with square footage:  2186


In [ ]:
sq_foots['the_data'].unique()

array(['2000', '9984', '10640', ..., '4,057 (Tax assessor)', '6,750',
       '23,447 SF'], dtype=object)

Looking at this data, we can see that some of the sqft's have commas and text in them, while others do not (are just a sequence of numbers). We will remove the commas and just extract the digits to transform the sqft column to be an integer type. There are also na values that we need to omit.

In [ ]:
# Remove NA's
sq_foots = sq_foots.dropna(subset=['the_data'])

# Replace commas and extract digits 
sq_foots['the_data'] = sq_foots['the_data'].str.replace(',', '')
sq_foots['the_data'] = sq_foots['the_data'].str.extract('(\d+)')

# Remove NA's
sq_foots = sq_foots.dropna(subset=['the_data'])

# Transform column to integers
sq_foots['the_data'] = sq_foots['the_data'].astype(float).astype(int)

In [ ]:
sq_foots

project_id              document_spot  the_data
562         494184  1f_summary_gross_building      2000
587         576666  1f_summary_gross_building      9984
1008        577861  1f_summary_gross_building     10640
1869        427876  1f_summary_gross_building      5000
2418        357520  1f_summary_gross_building     10282
...            ...                        ...       ...
557395      317124  1f_summary_gross_building     44049
557685      387690  1f_summary_gross_building     20354
557711      357629  1f_summary_gross_building      4057
557938      414286  1f_summary_gross_building      6750
558018      341545  1f_summary_gross_building     23447

[2172 rows x 3 columns]

Great! Now our data is all clean.

### Visualizing SQFT

In [ ]:
DeepnoteChart(sq_foots, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","color":"#2266D3","tooltip":true},"encoding":{"x":{"bin":{"maxbins":50},"axis":{"title":"SQFT"},"sort":null,"type":"quantitative","field":"the_data"},"y":{"axis":{"title":"Count"},"sort":null,"type":"quantitative","scale":{"type":"linear"},"format":{"type":"default","decimals":null},"aggregate":"count","formatType":"numberFormatFromNumberType"}}}]}],"title":"Histogram for SQFT","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{},"usermeta":{"aditionalTypeInfo":{"histogramLayerIndexes":[0]},"tooltipDefaultMode":true}}""")

In [ ]:
DeepnoteChart(sq_foots, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","color":"#2266D3","tooltip":true},"encoding":{"x":{"bin":{"maxbins":25},"axis":{"title":"SQFT"},"sort":null,"type":"quantitative","field":"the_data"},"y":{"axis":{"title":"Count"},"sort":null,"type":"quantitative","scale":{"type":"linear"},"format":{"type":"default","decimals":null},"aggregate":"count","formatType":"numberFormatFromNumberType"}}}]}],"title":"Histogram of SQFT < 50000","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{},"usermeta":{"aditionalTypeInfo":{"histogramLayerIndexes":[0]},"tooltipDefaultMode":true}}""")

The data is very skewed to the right.

<hr>

### Construction

In [ ]:
# Looking at the unique number of project_id for construction attributes in retail_simplified
# Vertical Constructions
vert_consts = retail_simplified[retail_simplified['document_spot'] == '42a_vertconst']
num_vc = len(vert_consts)
uniq_vc = vert_consts['project_id'].nunique()

print('Number of vertical constructions: ', num_vc)
print('Number of properties with vertical constructions: ', uniq_vc)

# Horizontal Constructions
horz_consts = retail_simplified[retail_simplified['document_spot'] == '42b_horzconst']
num_hc = len(horz_consts)
uniq_hc = horz_consts['project_id'].nunique()

print('Number of horizontal constructions: ', num_hc)
print('Number of properties with horizontal constructions: ', uniq_hc)

# Roof Constructions
horz_consts = retail_simplified[retail_simplified['document_spot'] == '42b_horzconst']
num_hc = len(horz_consts)
uniq_hc = horz_consts['project_id'].nunique()

print('Number of horizontal constructions: ', num_hc)
print('Number of properties with horizontal constructions: ', uniq_hc)

Number of vertical constructions:  2086
Number of properties with vertical constructions:  2086
Number of horizontal constructions:  1674
Number of properties with horizontal constructions:  1674
Number of horizontal constructions:  1674
Number of properties with horizontal constructions:  1674


Based on the number of unique properties for each attribute, there is no overlap.

### Examining unique values

In [ ]:
vert_consts['the_data'].unique()

array(['["Steel-framed"]',
       '["Conventional steel framing, isolated CMU, steel stud partition framing"]',
       '["Conventional wood stud platform with isolated CMU"]',
       '["Pre-engineered steel structure"]',
       '["Pre-engineered steel structure", "Conventional steel framing, isolated CMU, steel stud partition framing"]',
       '["Precast concrete wall panels, concrete columns, steel stud partition framing"]',
       '["CMU load bearing walls, steel columns, steel stud partition framing"]',
       '["Masonry wythe bearing walls, steel columns, steel stud partition framing"]',
       '["Light-gauge steel studs, CMU center core"]',
       '["Conventional wood stud platform"]',
       '["Tilt-up concrete walls & CIP columns, steel stud framing"]',
       '["CMU load-bearing exterior wall, concrete columns, steel stud partition framing"]',
       '["Concrete masonry unit load bearing walls with interior steel columns"]',
       '["Wood-framed"]',
       '["CMU load bearing

In [ ]:
horz_consts['the_data'].unique()

array(['["No upper floors present"]',
       '["Wood-framing with wood decking"]',
       '["Cast-in-place concrete with post tension concrete slabs"]',
       '["Wood-framing with wood decking and concrete topping"]',
       '["Conventional wood frame and wood decking "]',
       '["Steel-framed with steel decking"]',
       '["Mezzanine: Steel-framed and metal grating"]',
       '["Precast concrete T\'s"]',
       '["Steel-framed with steel decking and concrete topping"]',
       '["Open-web steel joists and metal decking with concrete fill"]',
       '["Prefabricated wood trusses and plywood decking"]',
       '["Conventional steel frame and metal deck with concrete fill"]',
       '["Cast-in-place concrete with concrete decking", "Conventional steel frame and metal deck with concrete fill"]',
       '["Cast-in-place concrete with concrete decking"]',
       '["Open-web steel joists with steel decking"]',
       '["Wood plank-and-beam framing"]',
       '["Precast concrete with conc

<hr>

## Exporting individual data files

### Zip codes

In [ ]:
# Using our zipcodes df from earlier to create a flipped 
# dataframe for just zipcodes
zipcodes = zipcodes.drop(columns=['document_spot'])
zipcodes = zipcodes.rename(columns={'the_data': 'zipcode'})

Exporting our clean data to Clean Retail Data (below)

In [ ]:
# Export zipcodes to folder
zipcodes.to_csv('Clean Retail Data/retail_zipcodes.csv', index=False)

<hr>

### Sqft

In [ ]:
# Using our sq_foots df from earlier to create a flipped
# dataframe for just square feet inputs
sq_foots = sq_foots.drop(columns=['document_spot'])
sq_foots = sq_foots.rename(columns={'the_data': 'sqft'})

Exporting our clean data to Clean Retail Data (below)

In [ ]:
# Export sq_foots to folder
sq_foots.to_csv('Clean Retail Data/retail_sqfts.csv', index=False)

<hr>

### Vertical Const & Horizontal Const & Roof Frame

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=aa72ad5b-4609-409b-ae7e-8a5fd2e73142' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>